### ISSUE TITLE
First time running postgres is not ready

### ISSUE THREAD

**Issue by Juleship** [BelkaLab/i18n-timezones#1]
This is the traceback:

```
Traceback (most recent call last):
  File "xliffTimeZone.py", line 141, in <module>
    main(sys.argv[1:])
  File "xliffTimeZone.py", line 83, in main
    conn = psycopg2.connect(conn_string)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "pg" (172.17.0.2) and accepting
	TCP/IP connections on port 5432?
```

**Comment by bertuz** [comment]
Thank you for pointing out! It has been fixed :o)
